Update termux-open-url

diff --git a/bin/termux-open-url b/bin/termux-open-url
--- a/bin/termux-open-url
+++ b/bin/termux-open-url
@@ -1,1 +1,47 @@
+#!/bin/bash
 
+clear
+echo "========================="
+echo "Descargar desde Youtube"
+echo "1.-Descargar en 2160p"
+echo "2.-Descargar en 1440p"
+echo "3.-Descargar en 1080p"
+echo "4.-Descargar en 720p"
+echo "5.-Descargar en 480p"
+echo "6.-Descargar en 360p"
+echo "7.-Descargar MP3"
+echo "*.-Salir"
+echo "========================="
+
+#Path donde se descargara el video (Hay que descomentar la linea y aadir '-P $path' al final de cada opcion)
+path=$HOME
+
+read -p "Inserte la opcion: " opcion
+case $opcion in
+
+        1)
+                yt-dlp -f 'bestvideo[height<=2160][ext=mp4]+bestaudio[ext=m4a]/best[height<=2160][ext=mp4]/best[ext=mp4]/best' -P $path --output "%(title)s.%(ext)s" $1
+                ;;
+        2)
+                yt-dlp -f 'bestvideo[height<=1440][ext=mp4]+bestaudio[ext=m4a]/best[height<=1440][ext=mp4]/best[ext=mp4]/best' -P $path --output "%(title)s.%(ext)s" $1
+                ;;
+        3)
+                yt-dlp -f 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[height<=1080][ext=mp4]/best[ext=mp4]/best' -P $path --output "%(title)s.%(ext)s" $1
+                ;;
+        4)
+                yt-dlp -f 'bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[height<=720][ext=mp4]/best[ext=mp4]/best' -P $path --output "%(title)s.%(ext)s" $1
+                ;;
+        5)
+                yt-dlp -f 'bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best[height<=480][ext=mp4]/best[ext=mp4]/best' -P $path --output "%(title)s.%(ext)s" $1
+                ;;
+        6)
+                yt-dlp -f 'bestvideo[height<=360][ext=mp4]+bestaudio[ext=m4a]/best[height<=360][ext=mp4]/best[ext=mp4]/best' -P $path --output "%(title)s.%(ext)s" $1
+                ;;
+        7)
+                yt-dlp --extract-audio --embed-metadata --embed-thumbnail --audio-format mp3 --audio-quality 0 -P $path --output "%(title)s.%(ext)s" $1
+                ;;
+        *)
+                echo "Variable invalida"
+                exit 1
+        ;;
+esac
